server:
  port: 8099
  servlet.context-path: /hmx_cmp
spring:  
  datasource:
#    url: jdbc:mysql://47.107.170.192:3306/hmx_schema?
    url: jdbc:mysql://120.24.222.160:3306/new_schema?
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
  jmx:
    enabled: false
  redis:
    database: 0
    host: 120.24.222.160
    port: 6379
    password:
    timeout: 5000ms #超时时间
    jedis:
      pool:
        max-active: 10 #最大连接数
        max-idle: 10 #最大空闲连接 默认8
        max-wait: -1ms #默认-1 最大连接阻塞等待时间
        min-idle: 5 #最小空闲连接
  servlet:
      multipart:
        max-file-size : 1024mb
        max-request-size : 1589mb
  http:
      encoding:
        charset: UTF-8
        enabled: true
        force: true

#打印sql脚本
#logging:
#  level:
#    com.hmx: debug
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

mybatis:
  mapper-locations: classpath*:com/hmx/*/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
#黄梅戏短信接入配置
SMSSendUrl: http://jk.106api.cn/smsUTF8.aspx
SMSUserName: hmx008
SMSPassword: F11A3E1A905E68D15C8FCA6DFD022630
SMSGwid: b89c4aec
SMSVerificationTemplate: "【黄梅戏资源库】您的验证码是code，请在一分钟内进行验证!"

#阿里oos accessKeyId accessKeySecret
accessKeyId: LTAIaeZo5lNZpDBd
accessKeySecret: HSB7GdPp998ziaGiVK6rgbrHhHSwAl
imageType: default
#默认png
imageExt: png,jpg,jpeg,gif
videoExt: MP4,MP3,FLV,HLS,TS,3GP,MPG,MPEG,MPE,DAT,VOB,ASF,AVI,WMV,ASF,FLV,F4V,RM,RMVB,MOV,MKV,M3U8,DV,GIF,M2T,M4V,MJ2,MJPEG,MTS,OGG,QT,SWF,WEBM
#阿里文件上传：pdf,epub  --测试环境
#oss:
#  endpoint: http://oss-cn-hangzhou.aliyuncs.com
#  accessKeyId: LTAIk9cA9ccLsyak
#  accessKeySecret: LN0d98MfMdc8WJb8qsBmlEaTNLaoq6
#  bucketName: zhonghuazhu
#  ossIsFormal: false
#  physicsrootpath: C:\\files
#  serverip: https://zhonghuazhu.oss-cn-hangzhou.aliyuncs.com
#阿里文件上传：pdf,epub  --生产环境
oss:
  endpoint:     http://oss-cn-hangzhou.aliyuncs.com
  accessKeyId: LTAIfeQo2pX120Qx
  accessKeySecret: Jcivacpj41iXupfCYl4ReeEXv3qTkU
  bucketName:   aqhmx
  ossisFormal:    false
  physicsrootpath:  c:\\files
  serverip:   https://aqhmx.oss-cn-hangzhou.aliyuncs.com
  ossIsFormal: false

    