server:
  port: 8090

spring:  
  datasource:
#    url: jdbc:mysql://47.98.248.104:3306/hmx_schema?
    url: jdbc:mysql://120.24.222.160:3306/new_schema
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
  jmx:
    enabled: false
  servlet:
      multipart:
        max-file-size : 1024mb
        max-request-size : 1589mb

#打印sql脚本
#logging:
#  level:
#    com.hmx: debug
#log4j:
#  logger:
#    com.hmx: debug
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true

  mapper-locations: classpath*:com/hmx/*/mapper/*.xml

#黄梅戏短信接入配置
SMSSendUrl: http://jk.106api.cn/smsUTF8.aspx
SMSUserName: hmx008
SMSPassword: F11A3E1A905E68D15C8FCA6DFD022630
SMSGwid: b89c4aec
SMSVerificationTemplate: "【黄梅戏资源库】您的验证码是code，请在一分钟内进行验证!"

#阿里oos accessKeyId accessKeySecret
accessKeyId: LTAIaeZo5lNZpDBd
accessKeySecret: HSB7GdPp998ziaGiVK6rgbrHhHSwAl
imageType: default
#默认png
imageExt: png,jpg,jpeg,gif
videoExt: MP4,MP3,FLV,HLS,TS,3GP,MPG,MPEG,MPE,DAT,VOB,ASF,AVI,WMV,ASF,FLV,F4V,RM,RMVB,MOV,MKV,M3U8,DV,GIF,M2T,M4V,MJ2,MJPEG,MTS,OGG,QT,SWF,WEBM
#阿里文件上传：pdf,epub
oss: 
  endpoint: http://oss-cn-hangzhou.aliyuncs.com
  accessKeyId: LTAIk9cA9ccLsyak
  accessKeySecret: LN0d98MfMdc8WJb8qsBmlEaTNLaoq6
  bucketName: zhonghuazhu
  ossIsFormal: false
  physicsrootpath: C:\\files
  serverip: https://zhonghuazhu.oss-cn-hangzhou.aliyuncs.com

live:
  appName: hmx   #应用名
  pushUrl: zb.ahich.cn  #推流域名
  pushKey: g8oYKiUUuH
  pullUrl: zb2.ahich.cn  #播流域名
  pullKey: 0RTdL2hsSQ